name: Deployment - Reusable Workflow

on:
  workflow_call:
    inputs:
      mongodb-uri:
        required: true
        type: string
      kubectl-version:
        description: provide the required Kubectl version
        default: v1.26.0
        required: false
        type: string
      k8s-manifest-dir:
        description: Directory containing Kubernetes manifest files
        default: kubernetes/
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: string
        required: true
    secrets:
      k8s_Kubeconfig:
        required: true
      mongodb-password:
        required: true

jobs:
  reuse-deploy:
    name: Reusable Deploy Job
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ steps.app-ingress-host.outputs.APP_INGRESS_HOST }}
    outputs:
      APP_INGRESS_URL: ${{ steps.app-ingress-host.outputs.APP_INGRESS_HOST }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install Kubectl CLI
        uses: azure/setup-kubectl@v4
        with:
          version: {{ inputs.kubectl-version }}

      - name: Setup Kubeconfig
        uses: azure/k8s-set-context@v5
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.k8s_Kubeconfig }}

      - name: Get Cluster Info
        run: |
          echo "kubectl version --short"

      - name: Get Nginx Ingress Controller IP
        #          run: |
        #            echo "INGRESS_IP=$(kubectl -n ingress-nginx get svc ingress-nginx-controller -o=jsonpath='{.status.loadbalancer.ingress[0].ip}')" >> GITHUB_ENV
        run: |
          echo "INGRESS_IP=172.234.45.65" >> "$GITHUB_ENV"     #For testing


      - name: Replace Token In Manifest Files
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["${{ inputs.k8s-manifest-dir }}*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/github-demo-repo:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: Check Files
        run: |
          cat kubernetes/development/*.yaml

      - name: Create Mongodb Secret
        run: |
          echo "kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
          --from-literal=MONGO_URI=${{ inputs.mongodb-uri }} \
          --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
          --from-literal=MONGO_PASSWORD=${{ secrets.mongodb-password }} \
          --save-config \
          --dry-run=client \
          -o yaml | kubectl apply -f -"

      - name: Deploy To Dev
        run: |
          echo "kubectl apply -f ${{ inputs.k8s-manifest-dir }}"

      - name: Get Application Ingress Host URL
        id: app-ingress-host
        #          run: |
        #            echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath='{.items[0].spec.tls.hosts[0]}')"
        run: |
          echo "APP_INGRESS_HOST=solar-system-${{ vars.NAMESPACE }}.${{ env.INGRESS_IP }}.nip.io" >> "$GITHUB_OUTPUT"